# Generated by Django 5.1.1 on 2024-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default='1', verbose_name='Количество'),
        ),
    ]
