# Generated by Django 5.1.1 on 2024-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('additional_info', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка')),
                ('category', models.CharField(choices=[('одежда', 'Одежда'), ('сувениры', 'Сувениры'), ('туристическое', 'Туристическое'), ('сумки', 'Сумки'), ('интерьер', 'Интерьер'), ('канцелярия', 'Канцелярия'), ('посуда', 'Посуда'), ('игрушки', 'Игрушки'), ('расходники', 'Расходники')], max_length=100, verbose_name='Категория')),
                ('quantity', models.IntegerField(verbose_name='Штук в наличии')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
