# Generated by Django 5.1.2 on 2024-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Цена товара'),
        ),
    ]
