# Generated by Django 4.2.8 on 2025-03-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.CharField(max_length=300, verbose_name='Категория')),
                ('category', models.CharField(max_length=300, verbose_name='Подкатегория')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название товара'),
        ),
    ]
