# Generated by Django 4.2.8 on 2025-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_categories_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Класс изображения'),
        ),
    ]
