# Generated by Django 5.1.2 on 2024-11-01 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='orders',
            name='summ',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
