# Generated by Django 5.1.2 on 2024-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orders_date_orders_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='summ',
            field=models.FloatField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
