# Generated by Django 5.1.2 on 2024-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orders_id_yk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.CharField(default='', max_length=10000, verbose_name='Детали заказа'),
        ),
    ]
