# Generated by Django 5.1.2 on 2024-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_orders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='index',
            field=models.CharField(default='', max_length=20, verbose_name='Почтовый индекс'),
        ),
    ]
